### ISSUE TITLE
The Presidency - Media Development and Diversity Agency (MDDA) pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#54]
Public Entity

- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/MDDA%20-%20Report%20on%20Covid%20Expenditure.pdf)
- [Trusted Archive copy](https://web.archive.org/web/20201106210738/http://ocpo.treasury.gov.za/COVID19/Documents/MDDA%20-%20Report%20on%20Covid%20Expenditure.pdf) (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by carlvdm** [comment]
May I grab this one? :)

**Comment by schalkventer** [comment]
All yours @carlvdm

**Comment by carlvdm** [comment]
In this case there are 2 tables with identical contents.

May I upload it only once instead of duplicated?
It appears that they're answering the two questions with the same answer.

![Screenshot from 2020-10-03 13-42-40](https://user-images.githubusercontent.com/25169028/94990729-8d535900-057e-11eb-8f59-927dff33203b.png)
![Screenshot from 2020-10-03 13-42-44](https://user-images.githubusercontent.com/25169028/94990731-904e4980-057e-11eb-994c-55ad34ef394a.png)

**Comment by tristynferreiro** [comment]
Uploaded :D
